Article:
    type: entity
    table: article
    uniqueConstraints:
        NOM:
            columns:
                - NOM
    id:
        idArticle:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_ARTICLE
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: NOM
        prix:
            type: decimal
            nullable: false
            precision: 17
            scale: 2
            column: PRIX
        description:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
                default: !!binary UGFzIGRlIGRlc2NyaXB0aW9uIGTpZmluaWU=
            column: DESCRIPTION
        urlImage:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
            column: URL_IMAGE
    lifecycleCallbacks: {  }
