Client:
    type: entity
    table: CLIENT
    uniqueConstraints:
        EMAIL:
            columns:
                - EMAIL
    id:
        idClient:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_CLIENT
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: NOM
        prenom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: PRENOM
        commune:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: COMMUNE
        codePostal:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: CODE_POSTAL
        voie:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: VOIE
        numeroVoie:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: NUMERO_VOIE
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: EMAIL
        pass:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: PASS
        telephone:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: TELEPHONE
    lifecycleCallbacks: {  }
